#!/usr/bin/env python3
"""findings.py — the findings ledger, and the closure invariant it enforces.

Written 2026-09-09, the day a memory entry was found asserting that a review
finding had forced a claim's withdrawal while the claim sat unchanged in the
published essay for two months. The review pipeline was never the weak
component. Transmission was — the distance between a finding and the artifact
it was supposed to change.

THE INVARIANT, and the only reason this file exists:

    A finding may not be recorded as resolved unless (a) it names the commit
    that resolved it, and (b) a check runs against the CURRENT artifact and
    passes. Not a note saying the fix was made. A reference to the thing that
    shows it, re-verified every time anyone asks.

So `resolve` refuses without a commit, and `verify` re-runs every resolved
finding's check against the file as it is on disk right now. A prose changelog
written by the drafting author can claim a repair the text never received;
this cannot, because the claim and the check are the same record.

`changelog` generates revision history from the ledger plus git. The essay's
Appendix B keeps only the provenance narrative that carries argumentative
weight — the retraction, the authorship, the commissioning rules. The list of
what changed is machinery, and machinery should be held by a program.

Usage:
  findings.py verify   [<artifact>]        # THE embarrassing question, as a command
  findings.py list     [<artifact>] [--status S] [--source S]
  findings.py show     <id>
  findings.py changelog <artifact> [--markdown]
  findings.py build    <artifact>          # regenerate changelog between markers in the file
  findings.py add      <artifact> --source S --summary "..." [--found DATE] [--mode M]
  findings.py resolve  <id> --commit SHA [--absent "..."]... [--present "..."]...
  findings.py reject   <id> --why "..."

Ledger: writing/findings/<artifact-basename>.json
Exit codes: verify returns 1 if any resolved finding fails its check.
"""
import argparse, json, os, subprocess, sys, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER_DIR = os.path.join(ROOT, "writing", "findings")
BEGIN = "<!-- FINDINGS:CHANGELOG:BEGIN — generated by bin/findings.py; do not hand-edit -->"
END = "<!-- FINDINGS:CHANGELOG:END -->"

OPEN, ACCEPTED, RESOLVED, REJECTED = "open", "accepted", "resolved", "rejected"


def ledger_path(artifact):
    base = os.path.basename(artifact)
    for ext in (".md", ".org", ".txt"):
        if base.endswith(ext):
            base = base[: -len(ext)]
    return os.path.join(LEDGER_DIR, base + ".json")


def load(artifact):
    p = ledger_path(artifact)
    if not os.path.exists(p):
        return {"artifact": artifact, "findings": []}
    with open(p) as f:
        return json.load(f)


def save(led):
    os.makedirs(LEDGER_DIR, exist_ok=True)
    p = ledger_path(led["artifact"])
    with open(p, "w") as f:
        json.dump(led, f, indent=2, ensure_ascii=False)
        f.write("\n")
    return p


def artifact_text(artifact, strip_generated=True):
    """The text a check runs against.

    The generated changelog is excluded by default. A finding's summary often
    quotes the very string its check forbids — "the orphaned '### Changelog'
    heading" — and once that summary is rendered into the artifact, the check
    matches its own description and reports a repair as undone. Twice on the
    first day. Checks are about the authored prose; the generated block is
    machinery and is not evidence about it either way.
    """
    p = artifact if os.path.isabs(artifact) else os.path.join(ROOT, artifact)
    with open(p, encoding="utf-8") as f:
        text = f.read()
    if strip_generated and BEGIN in text and END in text:
        text = text[: text.index(BEGIN)] + text[text.index(END) + len(END):]
    return text


def commit_exists(sha):
    r = subprocess.run(["git", "-C", ROOT, "cat-file", "-e", sha + "^{commit}"],
                       capture_output=True)
    return r.returncode == 0


def commit_info(sha):
    r = subprocess.run(["git", "-C", ROOT, "log", "-1", "--format=%h|%ad|%s",
                        "--date=short", sha], capture_output=True, text=True)
    if r.returncode != 0:
        return None
    h, d, s = r.stdout.strip().split("|", 2)
    return {"short": h, "date": d, "subject": s}


def check_finding(f, text):
    """Return (ok, [failure strings]). A resolved finding must pass."""
    fails = []
    chk = f.get("check") or {}
    for s in chk.get("absent", []):
        if s in text:
            fails.append("STILL PRESENT: " + s[:70])
    for s in chk.get("present", []):
        if s not in text:
            fails.append("MISSING: " + s[:70])
    if f.get("status") == RESOLVED:
        if not f.get("resolved_in"):
            fails.append("resolved with no commit named")
        elif not commit_exists(f["resolved_in"]):
            fails.append("commit not in this repo: " + f["resolved_in"])
        if not chk.get("absent") and not chk.get("present"):
            fails.append("resolved with no verifiable check")
    return (not fails), fails


# ---------------------------------------------------------------- commands


def cmd_verify(args):
    led = load(args.artifact)
    text = artifact_text(led["artifact"])
    resolved = [f for f in led["findings"] if f["status"] == RESOLVED]
    bad = 0
    print(f"Verifying {len(resolved)} resolved findings against "
          f"{led['artifact']} as it is on disk\n")
    for f in resolved:
        ok, fails = check_finding(f, text)
        mark = "  ok " if ok else "FAIL "
        print(f"{mark} [{f['id']:>4}] {f['source']:<12} {f['summary'][:74]}")
        for x in fails:
            print(f"        └─ {x}")
            bad += 1
    counts = {}
    for f in led["findings"]:
        counts[f["status"]] = counts.get(f["status"], 0) + 1
    print("\n" + ", ".join(f"{v} {k}" for k, v in sorted(counts.items())))
    if bad:
        print(f"\n{bad} check(s) failed — the record claims a repair the artifact "
              f"does not show.")
        return 1
    print("\nEvery resolved finding is demonstrated by the current artifact.")
    return 0


def cmd_list(args):
    led = load(args.artifact)
    for f in led["findings"]:
        if args.status and f["status"] != args.status:
            continue
        if args.source and args.source.lower() not in f["source"].lower():
            continue
        c = f.get("resolved_in", "") or ""
        print(f"[{f['id']:>4}] {f['status']:<9} {f['source']:<12} {f['found']}  "
              f"{c[:8]:<9} {f['summary'][:70]}")
    return 0


def cmd_show(args):
    for name in os.listdir(LEDGER_DIR):
        if not name.endswith(".json"):
            continue
        with open(os.path.join(LEDGER_DIR, name)) as fh:
            led = json.load(fh)
        for f in led["findings"]:
            if f["id"] == args.id:
                print(json.dumps(f, indent=2, ensure_ascii=False))
                return 0
    print(f"no finding {args.id}", file=sys.stderr)
    return 1


def render_changelog(led):
    """Deterministic revision history: ledger + git, no authorial prose."""
    out = []
    passes = {}
    for f in led["findings"]:
        if f["status"] not in (RESOLVED, REJECTED):
            continue
        key = (f.get("pass_order", 99), f["source"], f.get("mode", ""), f["found"])
        passes.setdefault(key, []).append(f)

    for (order, source, mode, found), items in sorted(passes.items()):
        head = f"**{source}**"
        if mode:
            head += f", {mode}"
        head += f", {found}"
        out.append(head + f" — {len(items)} finding(s)")
        for f in sorted(items, key=lambda x: x["id"]):
            if f["status"] == REJECTED:
                out.append(f"- ~~{f['summary']}~~ — not accepted: {f.get('why','')}")
                continue
            ci = commit_info(f["resolved_in"]) if f.get("resolved_in") else None
            ref = f" `{ci['short']}`" if ci else " *(no commit)*"
            lag = ""
            if ci:
                try:
                    d0 = datetime.date.fromisoformat(f["found"])
                    d1 = datetime.date.fromisoformat(ci["date"])
                    days = (d1 - d0).days
                    # The gap between finding and fixing is the failure this
                    # ledger exists to make visible. It does not get to hide.
                    lag = (f" — resolved {ci['date']}, **{days} days after it was "
                           f"found**") if days > 1 else f" — resolved {ci['date']}"
                except ValueError:
                    lag = f" — resolved {ci['date']}"
            out.append(f"- {f['summary']}{ref}{lag}")
        out.append("")
    counts = {}
    for f in led["findings"]:
        counts[f["status"]] = counts.get(f["status"], 0) + 1
    total = len(led["findings"])
    summ = ", ".join(f"{v} {k}" for k, v in sorted(counts.items()))
    out.append(f"*{total} findings on this artifact: {summ}. Every entry above "
               f"names the commit that resolved it, and `bin/findings.py verify` "
               f"re-checks each one against the current text. Generated — not "
               f"written.*")
    return "\n".join(out)


def cmd_changelog(args):
    print(render_changelog(load(args.artifact)))
    return 0


def cmd_build(args):
    led = load(args.artifact)
    path = os.path.join(ROOT, led["artifact"])
    # build needs the markers, which artifact_text() strips for checking
    text = artifact_text(led["artifact"], strip_generated=False)
    if BEGIN not in text or END not in text:
        print(f"markers not found in {led['artifact']}; insert:\n{BEGIN}\n{END}",
              file=sys.stderr)
        return 1
    pre = text[: text.index(BEGIN) + len(BEGIN)]
    post = text[text.index(END):]
    new = pre + "\n\n" + render_changelog(led) + "\n\n" + post
    if new == text:
        print("changelog already current")
        return 0
    with open(path, "w", encoding="utf-8") as f:
        f.write(new)
    print(f"regenerated changelog in {led['artifact']}")
    return 0


def next_id(led, source):
    pre = "".join(c for c in source if c.isalpha())[:1].upper() or "F"
    n = 1 + sum(1 for f in led["findings"] if f["id"].startswith(pre))
    while any(f["id"] == f"{pre}{n}" for f in led["findings"]):
        n += 1
    return f"{pre}{n}"


def cmd_add(args):
    led = load(args.artifact)
    if args.id:
        # An id collision is silent and dangerous: `resolve` matches by id across
        # every ledger file, so a reused id lets one finding's check and commit be
        # overwritten by another's — and `verify` stays green, because the
        # substituted check is usually true of the artifact too. It then stops
        # watching what it was built to watch. Happened 2026-09-13; refused since.
        for name in os.listdir(LEDGER_DIR):
            if not name.endswith(".json"):
                continue
            with open(os.path.join(LEDGER_DIR, name)) as fh:
                for g in json.load(fh)["findings"]:
                    if g["id"] == args.id:
                        print(f"refused: id {args.id} already exists in {name} "
                              f"({g['summary'][:50]}). Pick another, or omit --id.",
                              file=sys.stderr)
                        return 1
    f = {
        "id": args.id or next_id(led, args.source),
        "source": args.source,
        "mode": args.mode or "",
        "found": args.found or datetime.date.today().isoformat(),
        "summary": args.summary,
        "status": OPEN,
        "resolved_in": "",
        "check": {"absent": [], "present": []},
    }
    led["findings"].append(f)
    save(led)
    print(f"added [{f['id']}] {f['summary'][:60]}")
    return 0


def cmd_resolve(args):
    """The closure invariant lives here. No commit, no resolution."""
    for name in os.listdir(LEDGER_DIR):
        if not name.endswith(".json"):
            continue
        p = os.path.join(LEDGER_DIR, name)
        with open(p) as fh:
            led = json.load(fh)
        for f in led["findings"]:
            if f["id"] != args.id:
                continue
            if not commit_exists(args.commit):
                print(f"refused: {args.commit} is not a commit in this repo",
                      file=sys.stderr)
                return 1
            chk = f.setdefault("check", {"absent": [], "present": []})
            chk["absent"] = list(args.absent or chk.get("absent", []))
            chk["present"] = list(args.present or chk.get("present", []))
            if not chk["absent"] and not chk["present"]:
                print("refused: a resolution needs a check that can fail "
                      "(--absent / --present)", file=sys.stderr)
                return 1
            text = artifact_text(led["artifact"])
            f["status"] = RESOLVED
            f["resolved_in"] = args.commit
            f["resolved_on"] = datetime.date.today().isoformat()
            ok, fails = check_finding(f, text)
            if not ok:
                print("refused: the check does not pass against the current "
                      "artifact:", file=sys.stderr)
                for x in fails:
                    print("  " + x, file=sys.stderr)
                return 1
            save(led)
            print(f"[{f['id']}] resolved in {args.commit}, check passes")
            return 0
    print(f"no finding {args.id}", file=sys.stderr)
    return 1


def cmd_reject(args):
    for name in os.listdir(LEDGER_DIR):
        if not name.endswith(".json"):
            continue
        p = os.path.join(LEDGER_DIR, name)
        with open(p) as fh:
            led = json.load(fh)
        for f in led["findings"]:
            if f["id"] == args.id:
                f["status"] = REJECTED
                f["why"] = args.why
                save(led)
                print(f"[{f['id']}] rejected: {args.why}")
                return 0
    return 1


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    DEF = "writing/essays/alignment-as-architecture-v5.md"

    p = sub.add_parser("verify"); p.add_argument("artifact", nargs="?", default=DEF)
    p.set_defaults(fn=cmd_verify)
    p = sub.add_parser("list"); p.add_argument("artifact", nargs="?", default=DEF)
    p.add_argument("--status"); p.add_argument("--source"); p.set_defaults(fn=cmd_list)
    p = sub.add_parser("show"); p.add_argument("id"); p.set_defaults(fn=cmd_show)
    p = sub.add_parser("changelog"); p.add_argument("artifact", nargs="?", default=DEF)
    p.set_defaults(fn=cmd_changelog)
    p = sub.add_parser("build"); p.add_argument("artifact", nargs="?", default=DEF)
    p.set_defaults(fn=cmd_build)
    p = sub.add_parser("add"); p.add_argument("artifact", nargs="?", default=DEF)
    p.add_argument("--source", required=True); p.add_argument("--summary", required=True)
    p.add_argument("--found"); p.add_argument("--mode"); p.add_argument("--id")
    p.set_defaults(fn=cmd_add)
    p = sub.add_parser("resolve"); p.add_argument("id")
    p.add_argument("--commit", required=True)
    p.add_argument("--absent", action="append"); p.add_argument("--present", action="append")
    p.set_defaults(fn=cmd_resolve)
    p = sub.add_parser("reject"); p.add_argument("id"); p.add_argument("--why", required=True)
    p.set_defaults(fn=cmd_reject)

    args = ap.parse_args()
    sys.exit(args.fn(args))


if __name__ == "__main__":
    main()
